Repository Ace-of-Space/Web-Project, pull requests merged in 2023-09, with the labels that each got.

#13 Bulk Updates - Public Dir
  public/images/dominic.png
  public/images/readme.md
  public/index.html
  public/js/readme.md
  public/readme.md
  public/styles/readme.md
Labels: documentation, enhancement, mod

#14 Updated Version - Aminata
  public/index.html
Labels: needs triage

#15 Fixing Navigations - index.html
  public/index.html
  public/styles/styles.css
Labels: mod

#16 New Look - update index.html
  public/images/dauda.png
  public/images/deleteit.txt
  public/images/dominic.png
  public/images/edit.pub
  public/images/readme.md
  public/images/team.jpeg
  public/index.html
  public/js/script.js
  public/styles/styles.css
Labels: mod

#18 Mod + Resource DIR
  public/aos-membership.html
  public/images/aminata.png
  public/images/elsie.png
  public/images/me.jpg
  public/images/solomon.png
  public/index.html
  public/resources/contact-form.css
  public/resources/contact-form.html
  public/resources/image-hover-effect.css
  public/resources/new-footer.css
  public/resources/new-footer.html
  public/resources/simple-footer-design.txt
  public/styles/styles.css
Labels: documentation, needs triage, mod

#19 Services Section - Removed
  public/index.html
  public/resources/services.css
  public/resources/services.txt
  public/styles/styles.css
Labels: needs triage, mod
