Repository Ace-of-Space/Web-Project, pull requests merged in 2023-08, with the labels that each got.

#2 Update index.html
  public/index.html
Labels: enhancement

#3 Create styles.css
  public/styles/styles.css
Labels: enhancement

#9 Styles Mod
  public/index.html
  public/styles/styles.css
Labels: help wanted

#10 Slight Update - Team's Webpage
  public/index.html
  public/styles/styles.css
Labels: needs triage, mod
